/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadIdRouteImport } from './routes/$threadId'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as OctoAppRouteImport } from './routes/octo-app'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const OctoAppRoute = OctoAppRouteImport.update({
  id: '/octo-app',
  path: '/octo-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analyzer': typeof AnalyzerRoute
  '/ide': typeof IdeRoute
  '/launch': typeof LaunchRoute
  '/octo-app': typeof OctoAppRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analyzer': typeof AnalyzerRoute
  '/ide': typeof IdeRoute
  '/launch': typeof LaunchRoute
  '/octo-app': typeof OctoAppRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analyzer': typeof AnalyzerRoute
  '/ide': typeof IdeRoute
  '/launch': typeof LaunchRoute
  '/octo-app': typeof OctoAppRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/analyzer'
    | '/ide'
    | '/launch'
    | '/octo-app'
    | '/settings'
    | '/simulator'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$threadId'
    | '/analyzer'
    | '/ide'
    | '/launch'
    | '/octo-app'
    | '/settings'
    | '/simulator'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/$threadId'
    | '/analyzer'
    | '/ide'
    | '/launch'
    | '/octo-app'
    | '/settings'
    | '/simulator'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadIdRoute: typeof ThreadIdRoute
  AnalyzerRoute: typeof AnalyzerRoute
  IdeRoute: typeof IdeRoute
  LaunchRoute: typeof LaunchRoute
  OctoAppRoute: typeof OctoAppRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$threadId': {
      id: '/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/octo-app': {
      id: '/octo-app'
      path: '/octo-app'
      fullPath: '/octo-app'
      preLoaderRoute: typeof OctoAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadIdRoute: ThreadIdRoute,
  AnalyzerRoute: AnalyzerRoute,
  IdeRoute: IdeRoute,
  LaunchRoute: LaunchRoute,
  OctoAppRoute: OctoAppRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
