/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadIdRouteImport } from './routes/$threadId'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as Bot24x7RouteImport } from './routes/bot-24x7'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as OctoAppRouteImport } from './routes/octo-app'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityCommunityIdRouteImport } from './routes/community/$communityId'
import { Route as PostPostIdRouteImport } from './routes/post/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const Bot24x7Route = Bot24x7RouteImport.update({
  id: '/bot-24x7',
  path: '/bot-24x7',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const OctoAppRoute = OctoAppRouteImport.update({
  id: '/octo-app',
  path: '/octo-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCommunityIdRoute = CommunityCommunityIdRouteImport.update({
  id: '/community/$communityId',
  path: '/community/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analyzer': typeof AnalyzerRoute
  '/bot-24x7': typeof Bot24x7Route
  '/ide': typeof IdeRoute
  '/launch': typeof LaunchRoute
  '/octo-app': typeof OctoAppRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/chat': typeof ApiChatRoute
  '/community/$communityId': typeof CommunityCommunityIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analyzer': typeof AnalyzerRoute
  '/bot-24x7': typeof Bot24x7Route
  '/ide': typeof IdeRoute
  '/launch': typeof LaunchRoute
  '/octo-app': typeof OctoAppRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/chat': typeof ApiChatRoute
  '/community/$communityId': typeof CommunityCommunityIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/community': typeof CommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analyzer': typeof AnalyzerRoute
  '/bot-24x7': typeof Bot24x7Route
  '/ide': typeof IdeRoute
  '/launch': typeof LaunchRoute
  '/octo-app': typeof OctoAppRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/chat': typeof ApiChatRoute
  '/community/$communityId': typeof CommunityCommunityIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/analyzer'
    | '/bot-24x7'
    | '/ide'
    | '/launch'
    | '/octo-app'
    | '/settings'
    | '/simulator'
    | '/api/chat'
    | '/community/$communityId'
    | '/post/$postId'
    | '/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$threadId'
    | '/analyzer'
    | '/bot-24x7'
    | '/ide'
    | '/launch'
    | '/octo-app'
    | '/settings'
    | '/simulator'
    | '/api/chat'
    | '/community/$communityId'
    | '/post/$postId'
    | '/community'
  id:
    | '__root__'
    | '/'
    | '/$threadId'
    | '/analyzer'
    | '/bot-24x7'
    | '/ide'
    | '/launch'
    | '/octo-app'
    | '/settings'
    | '/simulator'
    | '/api/chat'
    | '/community/$communityId'
    | '/post/$postId'
    | '/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadIdRoute: typeof ThreadIdRoute
  AnalyzerRoute: typeof AnalyzerRoute
  Bot24x7Route: typeof Bot24x7Route
  IdeRoute: typeof IdeRoute
  LaunchRoute: typeof LaunchRoute
  OctoAppRoute: typeof OctoAppRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiChatRoute: typeof ApiChatRoute
  CommunityCommunityIdRoute: typeof CommunityCommunityIdRoute
  PostPostIdRoute: typeof PostPostIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$threadId': {
      id: '/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-24x7': {
      id: '/bot-24x7'
      path: '/bot-24x7'
      fullPath: '/bot-24x7'
      preLoaderRoute: typeof Bot24x7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/octo-app': {
      id: '/octo-app'
      path: '/octo-app'
      fullPath: '/octo-app'
      preLoaderRoute: typeof OctoAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$communityId': {
      id: '/community/$communityId'
      path: '/community/$communityId'
      fullPath: '/community/$communityId'
      preLoaderRoute: typeof CommunityCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadIdRoute: ThreadIdRoute,
  AnalyzerRoute: AnalyzerRoute,
  Bot24x7Route: Bot24x7Route,
  IdeRoute: IdeRoute,
  LaunchRoute: LaunchRoute,
  OctoAppRoute: OctoAppRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  ApiChatRoute: ApiChatRoute,
  CommunityCommunityIdRoute: CommunityCommunityIdRoute,
  PostPostIdRoute: PostPostIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
